# Generated by Django 4.2.3 on 2024-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "Admin"), ("2", "Staff"), ("3", "User")],
                default="1",
                max_length=1,
            ),
        ),
    ]
