# Generated by Django 4.2.3 on 2024-03-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0002_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                default="static/media/avatar1.png",
                null=True,
                upload_to="static/uploads",
            ),
        ),
    ]
