# Generated by Django 4.2.3 on 2024-05-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0008_alter_bug_report_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug_report",
            name="bug_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
