# Generated by Django 4.2.3 on 2024-05-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0012_remove_bug_status_status_bug_status_bug_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bug_status",
            old_name="bug_status",
            new_name="status_of_bug",
        ),
    ]
