# Generated by Django 4.2.3 on 2024-05-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0013_rename_bug_status_bug_status_status_of_bug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bug_status",
            old_name="status_of_bug",
            new_name="status",
        ),
    ]
