# Generated by Django 4.2.3 on 2024-05-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0014_rename_status_of_bug_bug_status_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bug_report",
            name="priority",
            field=models.CharField(default="medium", max_length=10),
        ),
        migrations.AlterField(
            model_name="bug_report",
            name="department",
            field=models.CharField(
                choices=[("1", "Backend"), ("2", "Frontend"), ("3", "Other")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bug_report",
            name="impact_on_user",
            field=models.CharField(
                choices=[("1", "major"), ("2", "moderate"), ("3", "minor")],
                default="1",
                max_length=10,
            ),
        ),
    ]
