# Generated by Django 4.2.3 on 2024-05-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0015_bug_report_priority_alter_bug_report_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug_report",
            name="priority",
            field=models.CharField(default="medium", max_length=10, null=True),
        ),
    ]
