# Generated by Django 5.0.4 on 2024-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0016_alter_bug_report_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug_status",
            name="status",
            field=models.CharField(
                choices=[("1", "Open"), ("2", "In Progress"), ("3", "Resolved")],
                default="1",
                max_length=20,
            ),
        ),
    ]
