# Generated by Django 5.0.4 on 2024-05-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bugapp", "0020_alter_bug_report_bug_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bug_report",
            name="bug_image",
            field=models.ImageField(upload_to="uploads"),
        ),
    ]
